---
- name: Setup monitoring directories and configs
  ansible.builtin.include_tasks: setup.yml
  tags: [monitoring]

- name: Deploy monitoring stack
  ansible.builtin.include_tasks: deploy.yml
  tags: [monitoring, monitoring_deploy]
