---
app_name: devops-app
docker_image: "{{ dockerhub_username }}/{{ app_name }}"
docker_tag: "{{ docker_image_tag | default('latest') }}"
app_port: 5000
app_container_port: 8000
app_restart_policy: unless-stopped
app_healthcheck_path: /health
app_environment: {}
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"
web_app_wipe: false
