apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info.configName" . }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
