apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info.envConfigName" . }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.configEnv.appName | quote }}
  APP_ENV: {{ .Values.configEnv.environment | quote }}
  FEATURE_VISITS: {{ .Values.configEnv.featureVisits | quote }}
  LOG_LEVEL: {{ .Values.configEnv.logLevel | quote }}
