apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-info.fullname" . }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "devops-info.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.vault.enabled .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-{{ .Values.vault.injectFileName }}: {{ .Values.vault.secretPath | quote }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "devops-info.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: devops-core-course
    spec:
      serviceAccountName: {{ include "devops-info.serviceAccountName" . }}
      containers:
        - name: {{ include "devops-info.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "devops-info.envConfigName" . }}
            - secretRef:
                name: {{ include "devops-info.secretName" . }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops-info.configName" . }}
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "devops-info.pvcName" . }}
        {{- end }}
