---
- name: Deploy application
  hosts: webservers
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: web_app
      tags:
        - web_app
        - app_deploy
        - compose
