replicaCount: 1

image:
  tag: "latest"

configEnv:
  environment: "dev"
  logLevel: "debug"

service:
  type: NodePort
  nodePort: 30082

persistence:
  size: 100Mi

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5
