replicaCount: 3

image:
  repository: devops-info-service
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

labels:
  app.kubernetes.io/part-of: devops-core-course

podAnnotations: {}

serviceAccount:
  create: true
  name: ""

secrets:
  create: true
  name: ""
  username: "change-me"
  password: "change-me"

vault:
  enabled: false
  role: "devops-info-role"
  secretPath: "kv/data/devops-lab11/devops-info"
  injectFileName: "app-config"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  nodePort: 30080

containerPort: 8000

env:
  PORT: "8000"
  LOG_FORMAT: "json"
  RELEASE_VERSION: "v1"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  preInstall:
    enabled: true
    image: busybox:1.36
    command:
      - sh
      - -c
      - echo pre-install check && sleep 3 && echo pre-install ok
  postInstall:
    enabled: true
    image: busybox:1.36
    command:
      - sh
      - -c
      - echo post-install smoke test && sleep 3 && echo post-install ok
